version: '3.3'

services:
    rabbitmq:
        image: rabbitmq:3.9.13-management-alpine
        container_name: 'rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - app-net
    nginx:
        build:
            context: .
        ports:
            - 7777:7777
        networks:
            - app-net

networks:
    app-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.28.0.0/16
