version: '3.3'

services:
  db:
    image: postgres
    restart: on-failure
    environment:
      TZ: "Asia/Almaty"
      POSTGRES_PASSWORD: authorizationDB123
      POSTGRES_DB: authorization-db
      POSTGRES_USER: authorization
    ports:
      - "5435:5432"
    networks:
      - etaskify_app-net
  authorization:
    image: 'authorization-app'
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8082:8082"
    networks:
      - etaskify_app-net

networks:
  etaskify_app-net:
    external: true
